### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by Abolfazllinuxx** [fgrunewald/fast_forward#26]
INFO - Loading mapping files
INFO - Mapping universe - indices
INFO - Mapping universe - positions
Traceback (most recent call last):
  File "/home/abolfazl/.local/bin/ff_map", line 160, in <module>
    main()
  File "/home/abolfazl/.local/bin/ff_map", line 127, in main
    mapped_trajectory = forward_map_positions(mapped_atoms,
  File "/home/abolfazl/.local/lib/python3.9/site-packages/numba/core/dispatcher.py", line 688, in typeof_pyval
    tp = typeof(val, Purpose.argument)
  File "/home/abolfazl/.local/lib/python3.9/site-packages/numba/core/typing/typeof.py", line 33, in typeof
    ty = typeof_impl(val, c)
  File "/usr/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/abolfazl/.local/lib/python3.9/site-packages/numba/core/typing/typeof.py", line 50, in typeof_impl
    tp = getattr(val, "_numba_type_", None)
  File "/home/abolfazl/.local/lib/python3.9/site-packages/numba/typed/typedlist.py", line 283, in _numba_type_
    raise TypeError("invalid operation on untyped list")
TypeError: invalid operation on untyped list

**Comment by fgrunewald** [comment]
insufficient information; probably related to missing mapping files or misnamed residues
